### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto.docs#25]
For users:

- [x] Projects and experiment
- [x] Create a new experiment
- [x] LightspeedSearch
- [x] Control panel
- [x] How to record a variable
- [x] Setting model parameters
- [x] Setting simulation parameters
- [x] Running a simulation
- [x] How to plot something
- [x] Download model
- [x] Download results

For devs:

- [ ] Persistence bundle optional info
- [x] LightspeedSearch ( @gidili )
- [x] Control panel ( @gidili )

**Comment by tarelli** [comment]
@adrianq feel free to add to this!

**Comment by tarelli** [comment]
@travs how easy/painful it is to move the docs to markdown format like you did for openworm? I don't remember if you used some script or something like that? Thanks!

**Comment by travs** [comment]
@tarelli I used `pandoc` and a little shell script, and it wasn't too painful!
Check out [this](https://github.com/openworm/openworm_docs/tree/master/rst-to-md-conversion) and let me know if the instructions aren't totally clear.

The main pain point I found was manually updating relative links, which pandoc didn't seem to do a good job of correcting. There weren't enough to motivate me to automate it, but it wouldn't be too hard to write a script that does it if you have a large number.

**Comment by tarelli** [comment]
@travs thanks, I'll give it a try!

**Comment by tarelli** [comment]
@adrianq @gidili please I need help with this, see my fork https://github.com/tarelli/org.geppetto.docs/blob/master/source/usinggeppetto.rst

**Comment by tarelli** [comment]
@adrianq file:///Users/matteocantarelli/Documents/Development/org.geppetto.docs/builddir/treevisualizerW.html just saying :)

**Comment by tarelli** [comment]
Will be updated after the instance type refactoring is complete

**Comment by LordKrabo** [comment]
I'll keep on working on this for Sprint 75.

**Comment by LordKrabo** [comment]
Need to add this to sprint 76 I think.

**Comment by LordKrabo** [comment]
@gidili Are there any other parts of the documentation that you would like me to work on?

**Comment by LordKrabo** [comment]
Hey @gidili What should I work on for this documentation? More specifically, what parts are you working on currently?
