### ISSUE TITLE
See if in Sphinx we can replace the source button with an Edit button

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto.docs#42]

**Comment by LordKrabo** [comment]
As far as I can tell the documentation for modifying Sphinx is available here: http://www.sphinx-doc.org/en/stable/config.html. Out of interest, is the sphinx documentation hosted on geppetto.org?

**Comment by tarelli** [comment]
We are settling for the edit button at the bottom right corner which is already available.
