### ISSUE TITLE
Missing description of ArrayType in geppettomodel.md

### ISSUE THREAD

**Issue by lynxite** [openworm/org.geppetto.docs#65]
In geppettomodel.md, the description of ArrayType ends abruptly leaving an unfinished sentence. See line 165.
> **An ArrayType defines a type that when instantiated will result** A VisualType is an abstract EClass that defines a particular kind of type that can be visualised in the 3D environment. A VisualType only allows for a VisualValue to be associated to it (e.g. a Cylinder, a Sphere, an OBJ, etc.).

**Comment by tarelli** [comment]
@lynxite good catch! Fixed, for more information see also the JavaDoc http://docs.geppetto.org/en/latest/_static/javadoc/index.html (although the generated one is for Java the same applies also if using Python since the API is generated from the same schema)
